// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6IsCyZKTpU349WaSPDJwpdvePGGV1KJ8',
    appId: '1:550455957560:web:5d2f1aa7727ccf65922ecd',
    messagingSenderId: '550455957560',
    projectId: 'fruit-hub-c571f',
    authDomain: 'fruit-hub-c571f.firebaseapp.com',
    storageBucket: 'fruit-hub-c571f.firebasestorage.app',
    measurementId: 'G-0JTBD4ZMD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDslyrWrUuVwxYtDs6OM1YpZa2FPQIsOe8',
    appId: '1:550455957560:android:1ad9ab72c483e923922ecd',
    messagingSenderId: '550455957560',
    projectId: 'fruit-hub-c571f',
    storageBucket: 'fruit-hub-c571f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUJkHMkRX-UrK_9h24WyCmGTN1ADJ_wlY',
    appId: '1:550455957560:ios:1d73d85f3202fa2a922ecd',
    messagingSenderId: '550455957560',
    projectId: 'fruit-hub-c571f',
    storageBucket: 'fruit-hub-c571f.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUJkHMkRX-UrK_9h24WyCmGTN1ADJ_wlY',
    appId: '1:550455957560:ios:1d73d85f3202fa2a922ecd',
    messagingSenderId: '550455957560',
    projectId: 'fruit-hub-c571f',
    storageBucket: 'fruit-hub-c571f.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6IsCyZKTpU349WaSPDJwpdvePGGV1KJ8',
    appId: '1:550455957560:web:415902050a1008e2922ecd',
    messagingSenderId: '550455957560',
    projectId: 'fruit-hub-c571f',
    authDomain: 'fruit-hub-c571f.firebaseapp.com',
    storageBucket: 'fruit-hub-c571f.firebasestorage.app',
    measurementId: 'G-MRX343Y9NY',
  );
}
